; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
    ;LIST P=16F887a
    #include "p16f877a.inc"
    
    UDATA_SHR
W_TEMP RES 1
STATUS_TEMP RES 1
COUNT1 RES 1
COUNT2 RES 1
BANDERA RES 1
REG_10 RES 1
 
RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    MAIN                   ; go to beginning of program
    ORG 0x04
	GOTO RUTINA_INTERR
; TODO ADD INTERRUPTS HERE IF USED
    
    
    
MAIN_PROG CODE                      ; let linker place main program
 
RUTINA_INTERR:
    MOVWF W_TEMP;
    SWAPF STATUS, W;
    MOVWF STATUS_TEMP;
    
    BANKSEL INTCON;
    BTFSC INTCON, T0IF;
    BSF BANDERA, 0;
    BTFSC INTCON, T0IF;
    BCF INTCON, T0IF;
    
    SWAPF STATUS_TEMP, W
    MOVWF STATUS
    SWAPF W_TEMP, F
    SWAPF W_TEMP, W
    
    RETFIE;
    
CONFIGS:
    MOVLW .10;
    MOVWF REG_10;
    
    BANKSEL PORTB;
    CLRF PORTA;
    CLRF PORTB;
   
    BANKSEL TRISA;				; SELECIONA BANCO 1 DA RAM

    MOVLW	B'11011111'
    MOVWF	TRISA			; CONFIGURA I/O DO PORTA

    MOVLW	B'11110000'
    MOVWF	TRISB			; CONFIGURA I/O DO PORTB

   
    MOVLW	B'11000111'
    MOVWF	OPTION_REG		; CONFIGURA OPTIONS
				    ; PULL-UPs DESABILITADOS
				    ; INTER. NA BORDA DE SUBIDA DO RB0
				    ; TIMER0 INCREM. PELO CICLO DE M?QUINA
				    ; WDT   - 1:128
				    ; TIMER - 1:1
    MOVLW	B'01100000'		
    MOVWF	INTCON			; CONFIGURA INTERRUP??ES
				    ; HABILITA AS INT. DE TMR0 E PERIF.
    MOVLW	B'00000000'		
    MOVWF	PIE1			; CONFIGURA INTERRUP??ES
				    ; DESABILITA AS INT. DE TMR1 E TMR2


    MOVLW	B'00000111'
    MOVWF	ADCON1			; CONFIGURA CONVERSOR A/D
				    ; CONFIGURA PORTA E PORTE COMO I/O DIGITAL
    BSF INTCON, GIE;

    RETURN;
    
PASO60MILI:
    ;BANKSEL INTCON;
    ;BCF INTCON, T0IF;
    BCF BANDERA, 0;
    DECFSZ REG_10;
    RETURN;
    BSF BANDERA, 1;
    MOVLW .10;
    MOVWF REG_10;
    RETURN;

BLINK_LED:
    BANKSEL PORTB;
    MOVFW PORTB;
    XORLW B'00000010';
    MOVWF PORTB;
    BCF BANDERA, 1;
    RETURN;

MAIN    
    CALL CONFIGS;
    BANKSEL PORTB;
    BSF PORTB, RB1;                         
LOOP; loop forever
    CLRWDT;
    BTFSC BANDERA, 0;
    CALL PASO60MILI;
    BTFSC BANDERA, 1;
    CALL BLINK_LED;
    GOTO LOOP;

    END